export const IPC_CHANNELS = {
    getSnapshot: "app:getSnapshot",
    listSkills: "skills:list",
    getSession: "session:get",
    newSession: "session:new",
    deleteSession: "session:delete",
    deleteMessages: "session:deleteMessages",
    sendChat: "chat:send",
    cancelRun: "chat:cancelRun",
    removeQueuedMessage: "chat:removeQueuedMessage",
    updateAuthMode: "session:updateAuthMode",
    updateModel: "session:updateModel",
    updateConfig: "config:update",
    syncProviderModels: "config:syncProviderModels",
    onMessageAppended: "events:messageAppended",
    onSessionChanged: "events:sessionChanged",
    onBusyChanged: "events:busyChanged",
    onError: "events:error",
    onTodosChanged: "events:todosChanged",
    onQueueChanged: "events:queueChanged",
    onContextWarningChanged: "events:contextWarningChanged",
    onConfirmRequest: "ui:confirmRequest",
    confirmResponse: "ui:confirmResponse",
};
